In [1]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [2]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 731028439389643444
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 10067378176
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 17329671712555397462
 physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6"
 xla_global_id: 416903419]

In [17]:
import tensorflow as tf
import numpy as np
s=tf.constant("hello world!")
print(s)
a=tf.constant([[1.,2.],
   [3.,4.]])
b=tf.constant([[1.,1.],
   [0.,1.]])
c=tf.matmul(a,b)
d=tf.constant(10)
print(c)
print(type(c))
print(c.shape)
print(c.dtype)

#tensor obj to ndarray(:N dimention array)
n = c.numpy()
print(n)
print(type(n))

#Change to python native
pn = int(d)
print(pn)
print(type(pn))

tf.Tensor(b'hello world!', shape=(), dtype=string)
tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 2)
<dtype: 'float32'>
[[1. 3.]
 [3. 7.]]
<class 'numpy.ndarray'>
10
<class 'int'>


In [6]:
# Variable:tf.Variable()
import tensorflow as tf
a=tf.Variable(100)
b=tf.Variable(200)
c=tf.add(a,b)
print(a)
print(b)
print(c)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=200>
tf.Tensor(300, shape=(), dtype=int32)


### tf.Tensor: 텐서 객체
#### 텐서는 다차원 배열로 넘파이(NumPy) ndarray 객체와 비슷하며,
#### tf.Tensor 객체는 데이터 타입과 크기를 가지고 있다.
#### 또한 tf.Tensor는 GPU 같은 가속기 메모리에 상주할 수 있다.
#### 텐서플로는 텐서를 생성하고 이용하는 풍부한 연산 라이브러리(tf.add, tf.matmul, tf.linalg.inv 등.)를 제공하며
#### 연산수행 시 자동으로 텐서를 파이썬 네이티브(native) 타입으로 변환하여 연산한다

In [10]:
#Operatior
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(5))
print(tf.reduce_sum([10,5,3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)


#### 예를 들어 10이라는 값 하나는 scalar (점, 1차원? 0차원으로 이해)
#### [1 2 3]이라는 배열(array, list와는 다름)은 방향을 가지는 vector (1차원 = Rank1)
#### [[1. 2.] [3. 4.]] 2차원 배열 = 행렬(Matrix) = Rank2
#### [[[1 1][2 2]][[3 3][4 4]]] 3차원 = 3d-Tensor = Rank3