In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [2]:
arr = np.loadtxt("data-03-diabetes.csv",delimiter=',',dtype=np.float32)
print(arr.shape)
#학습 데이터 분리: 70%, 531개
#검증 데이터 분리: 30%, 228개
x_train = arr[:531,:-1]
x_test = arr[531:,:-1]
y_train = arr[:531,[-1]]
y_test = arr[531:,[-1]]
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(759, 9)
(531, 8) (228, 8) (531, 1) (228, 1)


In [3]:
W=tf.Variable(tf.random.normal([8,1]),name='weight')
b=tf.Variable(tf.random.normal([1]),name='bias')
print(W,b)

<tf.Variable 'weight:0' shape=(8, 1) dtype=float32, numpy=
array([[-0.18030666],
       [-0.95028627],
       [-0.03964049],
       [-0.7425406 ],
       [ 1.3231523 ],
       [-0.61854804],
       [ 0.85406643],
       [-0.08899953]], dtype=float32)> <tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.22652864], dtype=float32)>


In [4]:
#H(X) = sigmoid(W*X + b)
def hy(X):
    return tf.sigmoid(tf.matmul(X,W) + b) # value is between 0 to 1

In [5]:
#logloss, 2진분류 모델
def cost_func():
    cost = -tf.reduce_mean(y_train*tf.math.log(hy(x_train)) +
                         (1-y_train)*tf.math.log(1-hy(x_train)))
    return cost

In [6]:
#경사하강법 learning_rate(학습률)을 0.01로 설정하여 optimizer object 생성
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

In [7]:
print("===Start===")
for step in range(10000):
    opt.minimize(cost_func,var_list=[W,b])
    if step%1000 == 0:
        print('%d'%step,'cost:',cost_func().numpy())
print("===finished===")

===Start===
0 cost: 0.8006094
1000 cost: 0.48674077
2000 cost: 0.4866587
3000 cost: 0.4866587
4000 cost: 0.48665863
5000 cost: 0.4866587
6000 cost: 0.4866587
7000 cost: 0.4866587
8000 cost: 0.4866587
9000 cost: 0.4866587
===finished===


In [8]:
preds = tf.cast(hy(x_test) > 0.5,dtype=tf.float32)
tf.cast(tf.equal(y_test,preds),dtype=tf.float32)

<tf.Tensor: shape=(228, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
 

In [9]:
# 정확도 측정 : accuracy computation
def predict(X):
    return tf.cast(hy(X) > 0.5,dtype=tf.float32)

# 검증 데이터를 사용하여 예측 (70%:30%)
preds = predict(x_test)
accuracy = tf.reduce_mean(tf.cast(tf.equal(preds,y_test),dtype=tf.float32))
print(tf.reduce_sum(tf.cast(tf.equal(preds,y_test),dtype=tf.float32)))
print('Accuracy:',accuracy.numpy()) # Accuracy: 0.78070176
# print('Hypothesis:\n',hypothesis(x_test).numpy())
# print('Predict:\n',preds.numpy())

tf.Tensor(178.0, shape=(), dtype=float32)
Accuracy: 0.78070176
