In [1]:
# xor_nn
# 2진 분류 : Logistic Regression
# 활성화 함수 : sigmoid 함수 사용
# two Layers of Neural Network
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [2]:
# train data set 
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]

y_data = [[0],
          [1],
          [1],
          [0]]

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [3]:
#Layer1(Hidden layer)
#은닉층의 출력 사이즈는 어떤 값이라도 무관 (m,n) * (n,Z) = (Z,X)
W1=tf.Variable(tf.random.normal([2,2]),name='Weight1')
b1=tf.Variable(tf.random.normal([2]),name='Bias1')

def layer1(X):
    return tf.nn.relu(tf.matmul(X,W1)+b1)
#    return tf.sigmoid(tf.matmul(X,W1)+b1)

In [4]:
#Layer2
W2=tf.Variable(tf.random.normal([2,2]),name='Weight2')
b2=tf.Variable(tf.random.normal([2]),name='Bias2')

def layer2(X):
    return tf.nn.relu(tf.matmul(layer1(X),W2)+b2)
#    return tf.sigmoid(tf.matmul(layer1(X),W2)+b2)

In [5]:
#Layer3(Output layer)
#출력행이 맞아야 함 (X,n) * (n,l) = (Y,l)
W3=tf.Variable(tf.random.normal([2,1]),name='Weight3')
b3=tf.Variable(tf.random.normal([1]),name='Bias3')

def hy(X):
    return tf.sigmoid(tf.matmul(layer2(X),W3)+b3)

In [6]:
#logloss, 2진분류 모델
def cost_func():
    cost = -tf.reduce_mean(y_train*tf.math.log(hy(x_train)) +
                         (1-y_train)*tf.math.log(1-hy(x_train)))
    return cost

In [7]:
#경사하강법 learning_rate(학습률)을 0.01로 설정하여 optimizer object 생성
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

In [8]:
print("===Start===")
for step in range(5001):
    opt.minimize(cost_func,var_list=[W1,b1,W2,b2,W3,b3])
    if step%1000 == 0:
        print('%d'%step,'cost:',cost_func().numpy())
print("===finished===")

===Start===
0 cost: 0.66319364
1000 cost: 0.4774331
2000 cost: 0.477404
3000 cost: 0.47739112
4000 cost: 0.4773879
5000 cost: 0.4773867
===finished===


In [9]:
print(W1,'\n',b1,'\n\n',W2,'\n',b2,'\n\n',W3,'\n',b3)

<tf.Variable 'Weight1:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.34730235, -1.2073263 ],
       [-0.52223825, -0.97208333]], dtype=float32)> 
 <tf.Variable 'Bias1:0' shape=(2,) dtype=float32, numpy=array([0.31921372, 0.9184752 ], dtype=float32)> 

 <tf.Variable 'Weight2:0' shape=(2, 2) dtype=float32, numpy=
array([[ 2.974418 , -0.8765189],
       [ 2.463934 , -2.1432838]], dtype=float32)> 
 <tf.Variable 'Bias2:0' shape=(2,) dtype=float32, numpy=array([0.5129756, 1.1224456], dtype=float32)> 

 <tf.Variable 'Weight3:0' shape=(2, 1) dtype=float32, numpy=
array([[-3.0928898],
       [ 2.7633448]], dtype=float32)> 
 <tf.Variable 'Bias3:0' shape=(1,) dtype=float32, numpy=array([-0.82199013], dtype=float32)>


In [10]:
def predict(X):
    return tf.cast(hy(X) > 0.5,dtype=tf.float32)
preds = predict(x_train)
accuracy = tf.reduce_mean(tf.cast(tf.equal(preds,y_train),dtype=tf.float32))
print('Accuracy:',accuracy.numpy())
print(preds)

Accuracy: 0.75
tf.Tensor(
[[0.]
 [1.]
 [1.]
 [1.]], shape=(4, 1), dtype=float32)
