# Keras Basic
### * Sequential Layer 의 주요 레이어 정리 
#### [1]  Dense Layer : Fully Connected Layer, layer의 입력과 출력 사이에 있는 모든 뉴런이 서로 연결 되는 Layer
#### [2]  Flatten Layer : 다차원(4차원)을 2차원으로 축소하여 FC Layer에 전달한다
#### [3]  Conv2D Layer : 이미지 특징을 추출하는 Convolution Layer 
#### [4]  MaxPool2D Layer : 중요 데이터(값이 큰 데이터)를 subsampling 하는 Layer
#### [5]  Dropout Layer : 학습시 신경망의 과적합을 막기위해 일부 뉴런을 제거하는 Layer

#### https://greeksharifa.github.io/keras/2018/06/29/Keras-Tutorial/

### [1] Dance layer

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# train data set 
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]   # (4,2)

y_data = [[0],
          [1],
          [1],
          [0]]     # (4,1)

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [18]:
#Dense Layer
#class이므로 instance 생성필요
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=4,activation='relu',input_shape=(2,)),
    tf.keras.layers.Dense(units=1,activation='sigmoid')
    # (m,n) * (n,l) = (m,l)
    # units 출력 사이즈 l 
    # input_shape 입력 사이즈 중 첫 요소 제거한 배열 n
]) 

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
             loss='binary_crossentropy',
             metrics=['accuracy'])

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_13 (Dense)            (None, 4)                 12        
                                                                 
 dense_14 (Dense)            (None, 1)                 5         
                                                                 
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(x_train,y_train,epochs=100,batch_size=1)

Epoch 1/100
4/4 [==============================] - 0s 6ms/step - loss: 0.7396 - accuracy: 0.5000
Epoch 2/100
4/4 [==============================] - 0s 8ms/step - loss: 0.7303 - accuracy: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 8ms/step - loss: 0.7176 - accuracy: 0.5000
Epoch 4/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7135 - accuracy: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7063 - accuracy: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 7ms/step - loss: 0.7001 - accuracy: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 7ms/step - loss: 0.6976 - accuracy: 0.5000
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 0.6970 - accuracy: 0.5000
Epoch 9/100
4/4 [==============================] - 0s 5ms/step - loss: 0.6956 - accuracy: 0.0000e+00
Epoch 10/100
4/4 [==============================] - 0s 5ms/step - loss: 0.6950 - accuracy: 0.2500
Epoch 11/100
4/4 [=======

In [20]:
preds = model.predict(x_train)
np.round(preds)

1/1 [==============================] - 0s 28ms/step


array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [21]:
model.evaluate(x_train,y_train)

1/1 [==============================] - 0s 83ms/step - loss: 0.6931 - accuracy: 0.5000


[0.6931483745574951, 0.5]

### [2] Flatten layer

In [27]:
# 4차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28*10).reshape(1000,28,28,10).astype(np.float32)
print(data.shape) # (None,28,28,10)

#layer =tf.keras.layers.Flatten()
#outputs = layer(data)
outputs = tf.keras.layers.Flatten()(data)
print(outputs.shape)

(1000, 28, 28)
(1000, 784)


### [3] Dropout layer

In [28]:
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout
# The Dropout layer randomly sets input units to 0 with a frequency of rate 
# at each step during training time, which helps prevent overfitting. 
# Inputs not set to 0 are scaled up by 1/(1 - rate) such that the sum over all inputs is unchanged.

# Note that the Dropout layer only applies when training is set to True such that
# no values are dropped during inference. When using model.fit, training will be
# appropriately set
tf.random.set_seed(0)
data = np.arange(10).reshape(5,2).astype(np.float32)
print(data)

layer = tf.keras.layers.Dropout(0.3,input_shape=(2,))

outputs = layer(data,training=True)
# model.fit()호출 시는  학습 모드로 training=True가 되어 dropuout 적용
# model.evaluate() 호출 시는 예측 모드로 False가 되어 dropuout이 수행되지 않음
print(outputs) # 데이터의 30%는 0으로 나머지 데이터는  1/(1-0.3)으로 곱하여 scaled up된다
print(data*1/(1 - 0.3))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
tf.Tensor(
[[ 0.         0.       ]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.1428576]
 [ 8.571428  10.       ]
 [11.428572   0.       ]], shape=(5, 2), dtype=float32)
[[ 0.         1.4285715]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.142857 ]
 [ 8.571428  10.       ]
 [11.428572  12.857143 ]]
