In [1]:
import numpy as np
import pandas as pd

In [10]:
metrix_data = [[10,20,30,40],
        [1,2,3,4]]
tensor_data = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                [[21,22,23,24],[25,26,27,28],[29,30,31,32]],
                [[91,92,93,94],[95,96,97,98],[99,90,89,87]]]

arr3 = np.array(tensor_data,np.float16)
arr2 = np.array(metrix_data,np.int16)
print(arr3)
print(arr3.dtype)
print(type(arr3))
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)

arr3 = arr3.reshape(2,2,3,-1)
arr3 = arr3.flatten()
print(arr3)
print(arr3.shape)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[21. 22. 23. 24.]
  [25. 26. 27. 28.]
  [29. 30. 31. 32.]]

 [[91. 92. 93. 94.]
  [95. 96. 97. 98.]
  [99. 90. 89. 87.]]]
float16
<class 'numpy.ndarray'>
(3, 3, 4)
3
36
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 21. 22. 23. 24. 25. 26.
 27. 28. 29. 30. 31. 32. 91. 92. 93. 94. 95. 96. 97. 98. 99. 90. 89. 87.]
(36,)


In [3]:
print(arr2.shape)
print(arr2)
arr2 = arr2.reshape(-1,2)
print(arr2.shape)
print(arr2)
arr2 = arr2.reshape(-1,)
print(arr2.shape)
print(arr2)

(2, 4)
[[10 20 30 40]
 [ 1  2  3  4]]
(4, 2)
[[10 20]
 [30 40]
 [ 1  2]
 [ 3  4]]
(8,)
[10 20 30 40  1  2  3  4]


In [18]:
narr = np.arange(0,15,0.5).reshape(5,3,2)
larr = narr.tolist()
larr

[[[0.0, 0.5], [1.0, 1.5], [2.0, 2.5]],
 [[3.0, 3.5], [4.0, 4.5], [5.0, 5.5]],
 [[6.0, 6.5], [7.0, 7.5], [8.0, 8.5]],
 [[9.0, 9.5], [10.0, 10.5], [11.0, 11.5]],
 [[12.0, 12.5], [13.0, 13.5], [14.0, 14.5]]]